routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();
/*
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Route::resource('contacts', [App\Http\Controllers\ContactController::class, 'create']);
*/

Route::middleware('auth')->group(function () {
    //...
    Route::resource('contacts', ContactController::class);
});

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;
    protected $fillable = ['nombre', 'apellido', 'telefono', 'direccion'];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Contact;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::paginate(5);
        return view('contacts.index', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contacts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nombre' => 'required',
        ]);

        $contact = new Contact();
        $contact->nombre = $request->get('nombre');
        $contact->apellido = $request->get('apellido');
        $contact->telefono = $request->get('telefono');
        $contact->direccion = $request->get('direccion');
        $contact->save();

        return redirect()->route('contacts.index')->with('success','Contacto creado correctamente.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact = Contact::findOrFail($id);
        return view('contacts.edit', compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nombre' => 'required',
        ]);

        $contact = Contact::findOrFail($id);
        $contact->nombre = $request->get('nombre');
        $contact->apellido = $request->get('apellido');
        $contact->telefono = $request->get('telefono');
        $contact->direccion = $request->get('direccion');
        $contact->save();

        return redirect()->route('contacts.index')->with('success', 'Contacto actualizado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::findOrFail($id)->delete();
        return back()->with("success", "Proyecto creado");
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('contacts.index');
    }
}

resources/views/contacts/create.blade.php
@extends('layouts.app')
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <form action="{{ route('contacts.store') }}" method="post" enctype="multipart/form-data" onsubmit="return validar(this)">
        {{ csrf_field() }}  
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">Nuevo Contacto</h2>
            </div>
            <div class="panel-body" style="margin: 0px 200px 0px 0px">
                <div class="form-group {{ $errors->has('nombre') ? ' has-error' : '' }}">
                    <label for="name">Nombre</label>
                    <input type="text" name="nombre" value="{{ old('nombre') }}" class="form-control" maxlength="100" placeholder="Ingrese el nombre del contacto" required />
                    @if ($errors->has('nombre'))
                        <span class="help-block">
                            <strong>{{ $errors->first('nombre') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('apellido') ? ' has-error' : '' }}">
                    <label for="name">apellido</label>
                    <input type="text" name="apellido" value="{{ old('apellido') }}" class="form-control" maxlength="100" placeholder="Ingrese el Apellido del contacto" required />
                    @if ($errors->has('apellido'))
                        <span class="help-block">
                            <strong>{{ $errors->first('apellido') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('telefono') ? ' has-error' : '' }}">
                    <label for="name">telefono</label>
                    <input type="text" name="telefono" value="{{ old('telefono') }}" class="form-control" maxlength="100" placeholder="Ingrese el telefono del contacto" required />
                    @if ($errors->has('telefono'))
                        <span class="help-block">
                            <strong>{{ $errors->first('telefono') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('direccion') ? ' has-error' : '' }}">
                    <label for="name">direccion</label>
                    <input type="text" name="direccion" value="{{ old('direccion') }}" class="form-control" maxlength="100" placeholder="Ingrese la direccion del contacto" required />
                    @if ($errors->has('direccion'))
                        <span class="help-block">
                            <strong>{{ $errors->first('direccion') }}</strong>
                        </span>
                    @endif
                </div>
                
            </div>
  
            <div class="panel-footer">
                <input type="submit" class="btn btn-primary" value="Guardar" data-loading-text="Guardando..."/>
                <a href="{{  route('contacts.index') }}" class="btn btn-light">Cancelar</a>
            </div>
        </div>
    </form>
</main>
@endsection

resources/views/contacts/edit.blade.php
@extends('layouts.app')
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <form action="{{ route('contacts.update', $contact) }}" method="post" enctype="multipart/form-data">
        {{ method_field('PATCH') }}
        {{ csrf_field() }}
        <div class="panel panel-default">
            <div class="panel-heading">
            <h4 class="border-bottom py-2 mb-4">Editar - Contacto</h4>
            </div>
            <div class="panel-body" style="margin: 0px 200px 0px 0px">
                <div class="form-group {{ $errors->has('nombre') ? ' has-error' : '' }}">
                    <label>Nombre</label>
                    <input type="text" name="nombre" value="{{ old('nombre', $contact->nombre) }}" class="form-control" placeholder="Ingrese el nombre" required />
                    @if ($errors->has('nombre'))
                        <span class="help-block">
                            <strong>{{ $errors->first('nombre') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('apellido') ? ' has-error' : '' }}">
                    <label>apellido</label>
                    <input type="text" name="apellido" value="{{ old('apellido', $contact->apellido) }}" class="form-control" placeholder="Ingrese el apellido" required />
                    @if ($errors->has('apellido'))
                        <span class="help-block">
                            <strong>{{ $errors->first('apellido') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('telefono') ? ' has-error' : '' }}">
                    <label>telefono</label>
                    <input type="text" name="telefono" value="{{ old('telefono', $contact->telefono) }}" class="form-control" placeholder="Ingrese el telefono" required />
                    @if ($errors->has('telefono'))
                        <span class="help-block">
                            <strong>{{ $errors->first('telefono') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('direccion') ? ' has-error' : '' }}">
                    <label>direccion</label>
                    <input type="text" name="direccion" value="{{ old('direccion', $contact->direccion) }}" class="form-control" placeholder="Ingrese el direccion" required />
                    @if ($errors->has('direccion'))
                        <span class="help-block">
                            <strong>{{ $errors->first('direccion') }}</strong>
                        </span>
                    @endif
                </div>
                
            </div>
            <div class="panel-footer">
                <input type="submit" class="btn btn-primary" value="Guardar" data-loading-text="Guardando..."/>
                <a href="{{ route('contacts.index') }}" class="btn btn-light">Cancelar</a>
            </div>
        </div>
    </form>
</main> 
@endsection

resources/views/contacts/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container py-5">

    <p class="h1 text-center">Contactos</p>
    <hr>
    <div class="table-responsive">
        <table class="table" id="niveles">
            <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">apellido</th>
                    <th scope="col">Telefono</th>
                    <th scope="col">Dirección</th>
                    <th scope="col" style="text-align:center"><a href="{{ route('contacts.create') }}" class="h3"><i class="fas fa-plus-square text-success"></i></a></th>
                </tr>
            </thead>
          
            <tbody>
                @foreach ($contacts as $contact)
                    <tr>
                        <td>{{ $contact->nombre }}</td>
                        <td>{{ $contact->apellido }}</td>
                        <td>{{ $contact->telefono }}</td>
                        <td>{{ $contact->direccion }}</td>
                        <td class="d-flex justify-content-end">
                            <a href="{{ route('contacts.edit', $contact) }}" class="circulo waves-effect mr-2"
                                title="Editar">
                                <i class="fas fa-edit text-warning" aria-hidden="true"></i>
                            </a>
                            <form action="{{ route('contacts.destroy', $contact) }}" method="post">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="circulo waves-effect mr-2 border-0 bg-white" title="Eliminar"
                                    onclick="return confirm('¿Desea eliminar este registro?')">
                                    <i class="fas fa-trash-alt text-danger" aria-hidden="true"></i>
                                </button>
                            </form>
                        </>
                    </tr>
                @endforeach
            </tbody>
        </table>
        @if ($contacts)
        <div class="mt-3 d-flex justify-content-end">
            {{ $contacts->links() }}
        </div>
        @endif
        
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'AGENDA') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

        <!-- Google font CDN -->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
   <!-- Bootstrap -->
   <link rel="stylesheet" type="text/css" href="{{asset('css/template/bootstrap.min.css')}}">

   <!-- Font Awesome -->
   <link
   href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
   rel="stylesheet"
   />
   <!-- Google Fonts -->
   <link
   href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
   rel="stylesheet"
   />
   <!-- MDB -->
   <link
   href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css"
   rel="stylesheet"
   />

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

            {{-- BOOTSTRAP JS MODIFIED --}}
            <script type="text/javascript" src="{{asset('js/template/bootstrap.min.js')}}"></script>
            <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
            {{-- CDN DATATABLES BOOTSTRAP 4 JS --}}
            <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
        
            <!-- MDB -->
            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"></script>
        
</body>
</html>